prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                         # 추가 1
from django.conf.urls.static import static
from prj.views import HomeView
from prj.views import login
from prj.views import register

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('^login/', login.as_view(), name='login'),
    path('^register/', register.as_view(), name='register'),
    path('^UserCreateView/', register.as_view(), name='UserCreateView'),
    path('^UserCreateDoneTV/', register.as_view(), name='UserCreateDoneTV'),
    path(r'^accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('pizzas/', include('pizzas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:                                       # 추가 2
    import debug_toolbar                                 # 추가 2
    urlpatterns += [                                     # 추가 2
        path('__debug__/', include(debug_toolbar.urls)), # 추가 2
    ]                                                    # 추가 2

shop/urls.py
from django.urls import path, register_converter
from shop import views
from shop import converters

app_name = 'shop'

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('', views.item_list, name='item_list'),                        # 조회
    path('view/<int:pk>/', views.item_detail, name='item_detail'),      # 조회
    path('new/', views.item_new, name='item_new'),                      # 등록
    path('remove/<int:pk>/', views.item_remove, name='item_remove'),    # 삭제
    path('edit/<int:pk>/', views.item_edit, name='item_edit'),          # 수정
    path('excel/', views.response_excel),
    path('image/', views.response_image),
    path('mysum/<int:x>/<int:y>/', views.my_sum),
    path('archives/<yyyy:year>/', views.year_archive),
    path('test_templates/', views.test_templates),  # 추가
]

work/shop/urls.py
from django.urls import path, register_converter
from shop import views
from shop import converters

app_name = 'shop'

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('', views.item_list, name='item_list'),                        # 조회
    path('view/<int:pk>/', views.item_detail, name='item_detail'),      # 조회
    path('new/', views.item_new, name='item_new'),                      # 등록
    path('remove/<int:pk>/', views.item_remove, name='item_remove'),    # 삭제
    path('edit/<int:pk>/', views.item_edit, name='item_edit'),          # 수정
    path('excel/', views.response_excel),
    path('image/', views.response_image),
    path('mysum/<int:x>/<int:y>/', views.my_sum),
    path('archives/<yyyy:year>/', views.year_archive),
    path('test_templates/', views.test_templates),  # 추가
]

shop/models.py
from django.db import models
from django.urls import reverse


class Item(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    photo = models.ImageField()  # blank=True 지정하지 않은 경우
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:item_detail', kwargs={'pk': self.pk})

work/shop/models.py
from django.db import models
from django.urls import reverse


class Item(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    photo = models.ImageField()  # blank=True 지정하지 않은 경우
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:item_detail', kwargs={'pk': self.pk})

shop/views.py
import re
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
import requests
from PIL import Image, ImageDraw, ImageFont
import pandas as pd                           # 엑셀 요청 처리
from io import BytesIO
from urllib.parse import quote
from django.views.generic import CreateView, UpdateView
from .models import Item
from .form import ItemForm


item_new = CreateView.as_view(model=Item, form_class=ItemForm)
item_edit = UpdateView.as_view(model=Item, form_class=ItemForm)

# # b29) 장고 Form 활용한 ...
# def item_new(request, item=None):
#     if request.method == 'POST':
#         form = ItemForm(request.POST, request.FILES, instance=item)
#         if form.is_valid():
#             item = form.save()
#             # return redirect(item)
#             return redirect('shop:item_list')
#     else:
#         form = ItemForm(instance=item)
#
#     return render(request, 'shop/item_form.html', {'form': form, })

# def item_new(request, item=None):
#     error_list = []
#     initial = {}
#
#     if request.method == 'POST':
#         data = request.POST
#         files = request.FILES
#
#         name = data.get('name')
#         desc = data.get('desc')
#         price = data.get('price')
#         photo = files.get('photo')
#         is_published = data.get('is_published') in (True, 't', 'True', '1')
#
#         # 유효성 검사
#         if len(name) < 2:
#             error_list.append('name을 2글자 이상 입력해주세요.')
#
#         if re.match(r'^[\da-zA-Z\s]+$', desc):
#             error_list.append('한글을 입력해주세요.')
#
#         if not error_list:
#             # 저장 시도
#             if item is None:
#                 item = Item()
#
#             item.name = name
#             item.desc = desc
#             item.price = price
#             item.is_published = is_published
#             if photo:
#                 item.photo.save(photo.name, photo, save=False)
#
#             try:
#                 item.save()
#             except Exception as e:
#                 error_list.append(e)
#             else:
#                 # return redirect(item)  # item.get_absolute_url 호출됨
#                 return redirect('shop:item_list')
#
#         initial = {
#             'name': name,
#             'desc': desc,
#             'price': price,
#             'photo': photo,
#             'is_published': is_published,
#         }
#     else:
#         if item is not None:
#             initial = {
#                 'name': item.name,
#                 'desc': item.desc,
#                 'price': item.price,
#                 'photo': item.photo,
#                 'is_published': item.is_published,
#             }
#     return render(request, 'shop/item_form.html', {
#         'error_list': error_list,
#         'initial': initial,
#     })


# def item_edit(request, pk):
#     item = get_object_or_404(Item, pk=pk)
#     return item_new(request, item)


def item_remove(request, pk):
    item = get_object_or_404(Item, pk=pk)
    item.delete()
    return redirect('shop:item_list')


# def item_new(request):
#     print('request.GET:', request.GET)
#     print('request.POST:', request.POST)
#     print('request.FILES:', request.FILES)
#     return render(request, 'shop/item_form.html')


def item_list(request):
    items = Item.objects.all()
    # 키값이 'q'로 지정된 값이 없으면 None이 반환됨
    q = request.GET.get('q', '')  # 'q'로 지정된 값이 없으면 '' 반환
    if q:  # q가 널 아니면 qs에 filter 조건 추가
        items = items.filter(name__icontains=q)
    return render(request, 'shop/item_list.html', {
        'item_list': items,
        'q': q, })


def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_detail.html',
                  {'item': item})


def response_excel(request):
    df = pd.DataFrame([
        [100, 110, 120],
        [200, 210, 220],
    ])

    io = BytesIO()
    df.to_excel(io)
    io.seek(0)

    encoded_filename = quote('pandas.xlsx')     # '.xls'가 아니라 '.xlsx'
    response = HttpResponse(io, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = \
        "attachment; filename*=utf-8''{}".format(encoded_filename)
    return response

def response_image(request):
    ttf_path = 'C:/Windows/Fonts/H2PORL.TTF'  # 윈도우, 맥: '/Library/Fonts/AppleGothic.ttf'

    # 이미지 파일 다운로드 혹은 로컬 디스크 상의 이미지 직접 열기
    image_url = 'http://www.flowermeaning.com/flower-pics/Calla-Lily-Meaning.jpg'
    res = requests.get(image_url)  # 서버로 HTTP GET 요청하여, 응답 획득
    io = BytesIO(res.content)  # 응답의 Raw Body 메모리 파일 객체 BytesIO 인스턴스 생성
    io.seek(0)  # 파일의 처음으로 커서를 이동

    canvas = Image.open(io).convert('RGBA')  # 이미지 파일을 열고, RGBA 모드로 변환
    font = ImageFont.truetype(ttf_path, 40)  # 지정 경로의 TrueType 폰트, 폰트 크기40
    draw = ImageDraw.Draw(canvas)  # canvas에 대한 ImageDraw 객체 획득

    text = 'Smart IT, by logistex'
    left, top = 400, 400
    margin = 10
    width, height = font.getsize(text)
    right = left + width + margin
    bottom = top + height + margin
    draw.rectangle((left, top, right, bottom), (255, 255, 224))
    draw.text((left+5, top+5), text, font=font, fill=(20, 20, 20))

    response = HttpResponse(content_type='image/png')
    canvas.save(response, format='PNG')  # HttpResponse의 유사 파일 객체 특성 활용
    return response

def year_archive(request, year):
    if year is not None:
        return HttpResponse('{}년도 자료 입니다.'.format(year))
    else:
        return HttpResponse('해당년도 자료는 없습니다.')

def my_sum(request, x, y):
    result = x + y
    output = '{} = {} + {}'.format(result, x, y)
    return HttpResponse(output)

class MyClass:
    x = 10
    y = 20

def test_templates(requset):
    from django.template import Context, Template
    import datetime       # USE_TZ = True
    from django.utils import timezone   # TIME_ZONE = 'Asia/Seoul'
    from dateutil.parser import parse

    # 맥락 변수 사전
    my_dict = {'first_name': 'haewoong', 'last_name': 'Shin'}
    my_obj = MyClass()
    my_list = [1, 2, 3, 4]
    my_date = datetime.datetime.now()
    local_time = timezone.localtime()
    my_b_date1 = datetime.date(2019, 12, 29)
    my_b_date2 = parse('2010-12-29')
    my_b_datetime = datetime.datetime(2010, 12, 29, 17, 34, 56)
    my_string = '사랑하지 않으려면 떠나라. Love it or leave it.'

    context = Context({'my_dict': my_dict, 'my_obj': my_obj, 'my_list': my_list,
                       'my_date': my_date, 'local_time': local_time,
                       'my_b_date1': my_b_date1, 'my_b_date2': my_b_date2,
                       'my_b_datetime': my_b_datetime, 'my_string': my_string,
                       })
    template = Template(
        "사전 < my_dict.last_name >: {{ my_dict.last_name }} <br/>"
        + "객체 < my_obj.x >: {{ my_obj.x }} {{ my_obj.y }} <br/>"
        + "리스트 < my_list.0 >: {{ my_list.0 }} {{ my_list.2 }}: {{ my_list.2 }} <br/>"
        + "< my_dict.first_name|title >: {{ my_dict.first_name|title }} <br/>"
        + "{% verbatim myblock %}{% now 'Y-m-d H:i:s' %}"
        + "{% endverbatim myblock %} : {% now 'Y-m-d H:i:s' %} <br/>"
        + "< my_date > : {{ my_date }} <br/>"
        + "< local_time >: {{ local_time }} <br/>"
        + "< my_b_date1 >: {{ my_b_date1 }} <br/>"
        + "< my_b_date2 >: {{ my_b_date2 }} <br/>"
        + "< my_b_date1|date:'SHORT_DATE_FORMAT' >: {{ my_b_date1|date:'SHORT_DATE_FORMAT' }} <br/>"
        + "(마지막에 점이 찍힘!! 필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_b_date1|date:'Y년 m월 d일' >: {{ my_b_date1|date:'Y년 m월 d일' }} <br/>"
        # + "< my_b_date|date:'LONG_DATE_FORMAT' >(???)': {{ my_b_date|date:'LONG_DATE_FORMAT' }} <br/>"
        # + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>" # 오류!!
        + "< my_b_datetime >: {{ my_b_datetime }} <br/>"
        + "< my_b_datetime|date:'Y년 m월 d일' > < my_b_datetime|time:'H시 i분 s초' >: "
        + "{{ my_b_datetime|date:'Y년 m월 d일' }}  {{ my_b_datetime|time:'H시 i분 s초' }} <br/>"
        + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_string|lower|truncatewords:'4' >: {{ my_string|lower|truncatewords:'4' }} <br/>"
        + "< my_string|lower|truncatewords:4 >: {{ my_string|lower|truncatewords:4 }} <br/>"
        + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_string|lower|truncatechars:'12' >: {{ my_string|lower|truncatechars:'12' }} <br/>"
        +"(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
    )
    content = template.render(context)

    return HttpResponse(content)

work/shop/templates/shop/item_detail.html
{% extends './layout.html' %}
{% load humanize %}

{% block content %}
    {{ block.super }}
    <a href="{% url 'shop:item_list' %}">상품 목록으로 돌아가기</a><br/><br/>
    <form>
    <fieldset>
    <table>
        <thead>
            <th>필드</th><th>내용</th>
        </thead>
        <tbody>
        <tr>
            <td width="15%">id:</td>
            <td><input type="text" value={{ item.id }} style = "text-align:right;"></td>
        </tr>
        <tr>
            <td>상품:</td>
            <td><input type="text" value="{{ item.name }}"></td>
        </tr>
        <tr>
            <td>설명:</td>
            <td>
                <textarea cols="40" rows="10">{{ item.desc.strip }}</textarea>
            </td>
        </tr>
        <tr>
            <td>가격:</td>
            <td><input type="text" value="{{ item.price|intcomma }}"
                       style = "text-align:right;"> 원
            </td>
        </tr>
        <tr>
            <td>사진:</td>
            <td>
                {% if item.photo %}<img src="{{ item.photo.url }}"/>{% endif %}
            </td>
        </tr>
        <tr>
            <td>출시 여부:</td>
            <td>
                <input type="checkbox" name="item.is_published" value="1"
                       {% if item.is_published %}checked{% endif %} />
            </td>
        </tr>
        </tbody>
    </table>
    </fieldset>
    </form>

<a href="{% url 'shop:item_edit' item.pk %}">상품 정보 수정</a>
<a href="{% url 'shop:item_remove' item.pk %}">상품 정보 삭제</a>
{% endblock content %}

work/shop/templates/shop/item_form.html
{% extends './layout.html' %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="container">
        <div class="col-sm-12">
            {% if request.path == '/shop/new/' %}
                <h2>상품 등록</h2>
            {% elif request.path|slice:":11" == '/shop/edit/' %}
                <h2>상품 수정</h2>
            {% endif %}
            <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                <table class="table table-bordered">
                    {{ form.as_table }}
                </table>
                <input type="submit" value="저장하기" class="btn btn-primary" />
            </form>
        </div>
    </div>
{% endblock content %}

work/shop/templates/shop/item_form_old.html
{% extends './layout.html' %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="container">
        <div class="col-sm-12">
            {{ request.path }}
            {% if request.path == '/shop/new/' %}
                <h2>상품 등록</h2>
            {% elif request.path|slice:"5:11" == '/edit/' %}
                <h2>상품 수정</h2>
            {% endif %}

            {% if error_list %}
                <div class="alert alert-danger">
                    error_list: {{ error_list }}
                </div>
            {% endif %}

            {% if initial %}
                <div class="alert alert-info">
                    initial: {{ initial }}
                </div>
            {% endif %}

            <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}

                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th>상품 이름</th>
                            <td>
                                <input type="text" name="name" value="{{ initial.name }}" class="form-control" />
                            </td>
                        </tr>
                        <tr>
                            <th>상품 설명</th>
                            <td>
                                <textarea name="desc" class="form-control"
                                    cols="40" rows="10">{{ initial.desc }}</textarea>
                            </td>
                        </tr>
                        <tr>
                            <th>가격 (원)</th>
                            <td>
                                <input type="text" name="price" value="{{ initial.price }}" class="form-control" style="width:150px; text-align:right;"/>
                            </td>
                        </tr>
                        <tr>
                            <th>상품 사진</th>
                            <td>
                                {% if initial.photo %}<img src="{{ initial.photo.url }}"/>{% endif %}
                                <input type="file" name="photo"
                                       value="{{ initial.photo.url }}" class="form-control" />
                            </td>
                        </tr>
                        <tr>
                            <th>출시 여부</th>
                            <td>
                                <input type="checkbox" name="is_published" value="1"
                                       {% if initial.is_published %}checked{% endif %} />
                            </td>
                        </tr>
                    </tbody>
                </table>

                <input type="submit" value="저장하기" class="btn btn-primary" />
            </form>

        </div>
    </div>
{% endblock content %}

work/shop/templates/shop/item_list.html
<!-- shop/templates/shop/item_list.html -->
{% extends './layout.html' %}
{% load humanize %}

{% block content %}
    {{ block.super }}
    <form action="" method="GET">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="검색" />
    </form>
    <hr>
    <table>
        <thead>
            <th>번호</th>
            <th>이름</th>
            <th>설명</th>
            <th>가격</th>
            <th>사진</th>
            <th>출시 여부</th>
            <th>수정</th>
            <th>삭제</th>
        </thead>
        <tbody>
            {% for item in item_list %}
            <tr>
                <td align="right"> {{ item.id }} </td>
                <td>
                    <a href="{{ item.get_absolute_url }}">
                        {{ item.name }}
                    </a>
                </td>
                <td> {{ item.desc|truncatechars:15 }} </td>
                <td align="right"> {{ item.price|intcomma }} 원</td>
                <td> {{ item.photo }} </td>
                <td><input type="checkbox" name="item.is_published" value="1"
                       {% if item.is_published %}checked{% endif %} />
                </td>
                <td>
                    <a href="{% url 'shop:item_edit' item.pk %}">
                        수정
                    </a>
                </td>
                <td>
                    <a href="{% url 'shop:item_remove' item.pk %}">
                        삭제
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table> <br/><br/>

<a href="{% url 'shop:item_new' %}">새 상품 등록</a>

{#    {{ request }} <br/>#}
{#    request.method: {{ request.method }} <br/>#}
{#    request.GET: {{ request.GET }} <br/>#}
{#    request.META: {{ request.META }}#}
{#    <hr/>#}
{#    {{ item_list }}#}
{#    <hr>#}
{#    {% for item in item_list %}#}
{#        {{ item }} <br>#}
{#    {% endfor %}#}
{#    <hr>#}
{#    {% for item in item_list %}#}
{#        {{ item.name }} ##}
{#        {{ item.desc }} ##}
{#        {{ item.photo }} ##}
{#        {{ item.created_at }} ##}
{#        {{ item.updated_at }} <br/>#}
{#        {% if item.photo %}#}
{#            <img src="{{ item.photo.url }}" />#}
{#        {% endif %} <br/>#}
{#    {% endfor %}#}
{% endblock %}

work/shop/templates/shop/layout.html
<!-- shop/templates/shop/layout.html -->
{% extends '../layout.html' %}

{% load static %}

{% block title %}
    {{ block.super }} shop
{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'shop/shop.css' %}" />
{% endblock %}

{% block content %}
    {{ block.super }}
    <img src="{% static 'shop/com_shin.png' %}" alt="shop logo image">
    <h2>shop in logistex site </h2>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
    <script src="{% static 'shop/shop.js' %}"></script>
{% endblock %}